=== Leg0shii/University-Homework/Bachelor-Computer-Science/Semester3/SWT/DTD/BestellungDTD.dtd
<!ELEMENT BESTELLUNG (POSTEN+, KUNDE, BESTELLSUMME)>

<!ELEMENT POSTEN (ARTIKEL_NAME, ARTIKEL_ID, EINZELPREIS, STUECKZAHL, POSTENSUMME, AUFDRUCK?)>
<!ELEMENT KUNDE (KUNDEN_ID)>
<!ELEMENT AUFDRUCK ((LOGO, LTEXT?)|WAPPEN*)>

<!ELEMENT BESTELLSUMME (#PCDATA)> 
<!ELEMENT KUNDEN_ID (#PCDATA)> 
<!ELEMENT BESTELLSUMME (#PCDATA)> 
<!ELEMENT ARTIKEL_NAME (#PCDATA)> 
<!ELEMENT ARTIKEL_ID (#PCDATA)> 
<!ELEMENT EINZELPREIS (#PCDATA)> 
<!ELEMENT STUECKZAHL (#PCDATA)> 
<!ELEMENT POSTENSUMME (#PCDATA)> 
<!ELEMENT LOGO (#PCDATA)> 
<!ELEMENT LTEXT (#PCDATA)> 
<!ELEMENT WAPPEN (#PCDATA)> 

<!ATTLIST KUNDE 
    typ (privat | firma) #IMPLIED>
	
<!ATTLIST BESTELLUNG 
    id ID #REQUIRED>

=== Leg0shii/University-Homework/Bachelor-Computer-Science/Semester3/SWT/DTD/Order.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE LIST SYSTEM
        "C:\Users\benja\Desktop\Coding\20 Uni\University-Homework\Bachelor-Computer-Science\Semester3\SWT\DTD\BestellungDTD.dtd">

<BESTELLUNG id="B01"> 
	<POSTEN>
		<ARTIKEL_NAME> Jogginghose </ARTIKEL_NAME>
		<ARTIKEL_ID> 12345 </ARTIKEL_ID>
		<EINZELPREIS> 34,56 </EINZELPREIS>
		<STUECKZAHL> 2 </STUECKZAHL>
		<POSTENSUMME> 69,12 </POSTENSUMME>
	</POSTEN>
	<KUNDE typ="privat">
		<KUNDEN_ID> Kd001 </KUNDEN_ID>
	</KUNDE>
	<BESTELLSUMME> 69,12 </BESTELLSUMME>
</BESTELLUNG>
